import Providers from '../../redux/provider/provider'
import MainLayout from './Components/MainLayout'
import './globals.css'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Catastro',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Providers>

    <html lang="en">
   
          <body className={inter.className}>
            {children}
            
            </body>
        
        

     
    </html>
    </Providers>
  )
}
